name: Docker Build, Publish and Deploy

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  docker_build_and_publish:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.image_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Define_docker_image_tag
        id: image_tag
        run: |
          echo "DOCKER_IMAGE_TAG=$(git describe --tags)" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(git describe --tags)" >> "$GITHUB_OUTPUT"
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: 'linux/amd64'
          push: true
          tags: nethermindeth/juno:${{ env.DOCKER_IMAGE_TAG }}
    
  deploy_to_dev:
    permissions:
      id-token: write
      contents: write
    needs: [docker_build_and_publish]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Repository Dispatch Dev
        env:
          EVENT_NAME: juno-dev
          IMAGE_TAG: ${{ needs.docker_build_and_publish.outputs.IMAGE_TAG }}
          GOERLI: apps/juno-dev/overlays/dev-goerli-1/config.yaml
          INTEGRATION: apps/juno-dev/overlays/dev-integration/config.yaml
          MAINNET: apps/juno-dev/overlays/dev-mainnet/config.yaml
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/NethermindEth/argo/dispatches \
          -d '{"event_type": "${{ env.EVENT_NAME }}", "client_payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "integration_config": "${{ env.INTEGRATION }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'

  dev-starknet-rs-tests:
    needs: [deploy_to_dev]
    uses: ./.github/workflows/starknet-rs-tests.yml
    secrets:
      STARKNET_RPC: ${{ secrets.DEV_GOERLI_URL }}/v0_4
      
  dev-starknet-js-tests:
    needs: [deploy_to_dev]
    uses: ./.github/workflows/starknet-js-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.DEV_GOERLI_URL }}/v0_4
      TEST_ACCOUNT_ADDRESS: ${{ secrets.GOERLI_TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.GOERLI_TEST_ACCOUNT_PRIVATE_KEY }}

  approval-check:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [deploy_to_dev]
    steps:
      - name: Wait for 10 minutes
        run: sleep 600 
            
      - name: Check if workflow approval for previous job has been approved
        env:
          GH_TOKEN: ${{ github.token }}
        id: check_approvals
        run: |
          echo "Workflow approval for previous job has not been approved. ccanceling workflow..."
          gh api --method POST -H "Accept: application/vnd.github+json" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel
  
      # steps:
      #   - name: Wait for 5 minutes
      #     run: sleep 300 
  
      #   - name: Check for deployment review
      #     id: check_review
      #     run: |
      #       #   curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       #   https://api.github.com/repos/${{ github.repository }}/deployments/${{ github.event.deployment.id }}/statuses
            
      #   - name: Cancel job if no review
      #     if: steps.check_review.outputs.review_status != 'APPROVED'
      #     run: |
      #       #   curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       #   https://api.github.com/repos/${{ github.repository }}/actions/jobs/${{ github.job_id }}/cancel
            
  deploy_to_staging:
    needs: [docker_build_and_publish, deploy_to_dev]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    steps:         
    - name: Repository Dispatch Staging
      env:
          EVENT_NAME: juno-staging
          IMAGE_TAG: ${{ needs.docker_build_and_publish.outputs.IMAGE_TAG }}
          GOERLI: apps/juno-staging/overlays/staging-goerli-1/config.yaml
          INTEGRATION: apps/juno-staging/overlays/staging-integration/config.yaml
          MAINNET: apps/juno-staging/overlays/staging-mainnet/config.yaml
      run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/NethermindEth/argo/dispatches \
          -d '{"event_type": "${{ env.EVENT_NAME }}", "client_payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "integration_config": "${{ env.INTEGRATION }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'

  staging-starknet-rs-tests:
    needs: [deploy_to_staging]
    uses: ./.github/workflows/starknet-rs-tests.yml
    secrets:
      STARKNET_RPC: ${{ secrets.STAGING_GOERLI_URL }}/v0_4
      
  staging-starknet-js-tests:
    needs: [deploy_to_staging]
    uses: ./.github/workflows/starknet-js-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.STAGING_GOERLI_URL }}/v0_4
      TEST_ACCOUNT_ADDRESS: ${{ secrets.GOERLI_TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.GOERLI_TEST_ACCOUNT_PRIVATE_KEY }}

  deploy_to_production:
    needs: [docker_build_and_publish, deploy_to_staging]
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Repository Dispatch Prod
        env: 
          EVENT_NAME: juno-prod
          IMAGE_TAG: ${{ needs.docker_build_and_publish.outputs.IMAGE_TAG }}
          GOERLI: apps/juno-prod/overlays/prod_goerli-1/config.yaml
          INTEGRATION: apps/juno-prod/overlays/prod_integration/config.yaml
          MAINNET: apps/juno-prod/overlays/prod_mainnet/config.yaml
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/NethermindEth/argo/dispatches \
          -d '{"event_type": "${{ env.EVENT_NAME }}", "client_payload":{"name": "${{ env.EVENT_NAME }}", "goerli_config": "${{ env.GOERLI }}", "integration_config": "${{ env.INTEGRATION }}", "mainnet_config": "${{ env.MAINNET }}", "tag": "${{ env.IMAGE_TAG }}"}}'
          
  prod-starknet-rs-tests:
    needs: [deploy_to_production]
    uses: ./.github/workflows/starknet-rs-tests.yml
    secrets:
      STARKNET_RPC: ${{ secrets.PROD_GOERLI_URL }}/v0_4
      
  prod-starknet-js-tests:
    needs: [deploy_to_production]
    uses: ./.github/workflows/starknet-js-tests.yml
    secrets:
      TEST_RPC_URL: ${{ secrets.PROD_GOERLI_URL }}/v0_4
      TEST_ACCOUNT_ADDRESS: ${{ secrets.GOERLI_TEST_ACCOUNT_ADDRESS }}
      TEST_ACCOUNT_PRIVATE_KEY: ${{ secrets.GOERLI_TEST_ACCOUNT_PRIVATE_KEY }}

